name: .NET Core Windows Forms App

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Proyecto.sln
      Test_Project_Path: Proyecto.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Execute unit tests
      run: dotnet test ${{ env.Test_Project_Path }}

    - name: Restore the application
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=$env:Configuration
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Build the application using .NET Framework MSBuild
      run: |
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" $env:Solution_Name /p:Configuration=${{ matrix.configuration }}
      env:
        Configuration: ${{ matrix.configuration }}
      
    - name: Publish the application using .NET Framework MSBuild
      run: |
        cd $(dirname $env:Solution_Name)
        "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" $env:Solution_Name /t:Publish /p:Configuration=${{ matrix.configuration }} /p:OutputPath=${{ github.workspace }}/artifacts
      env:
        Configuration: ${{ matrix.configuration }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Build Artifacts ${{ matrix.configuration }}
        path: ${{ github.workspace }}/artifacts
